// Codepoints for Material Symbols Rounded (variable font, default instance).
// Generated from google/material-design-icons MaterialSymbolsRounded.codepoints.
export const ICON_GLYPHS = {
  health_and_safety: '\u{e1d5}',
  visibility_off: '\u{e8f5}',
  check_box: '\u{e9de}',
  fingerprint: '\u{e90d}',
  signal_cellular_alt: '\u{e202}',
  wifi: '\u{e63e}',
  battery_full: '\u{e1a5}',
  notifications: '\u{e7f5}',
  restart_alt: '\u{f053}',
  pending_actions: '\u{f1bb}',
  chevron_right: '\u{e5cc}',
  inbox: '\u{e156}',
  search: '\u{ef7a}',
  expand_more: '\u{e5cf}',
  filter_alt_off: '\u{eb32}',
  arrow_back: '\u{e5c4}',
  bookmark_border: '\u{e8e7}',
  share: '\u{e80d}',
  location_on: '\u{f1db}',
  event: '\u{e878}',
  bed: '\u{efdf}',
  restaurant: '\u{e56c}',
  check_circle: '\u{f0be}',
  error: '\u{f8b6}',
  chevron_left: '\u{e5cb}',
  task_alt: '\u{e2e6}',
  remove: '\u{e15b}',
  add: '\u{e145}',
  arrow_forward: '\u{e5c8}',
  draw: '\u{e746}',
  receipt_long: '\u{ef6e}',
  calendar_month: '\u{ebcc}',
  person: '\u{f0d3}',
  home: '\u{e9b2}',
  group_add: '\u{e7f0}',
  warning: '\u{f083}',
  schedule: '\u{efd6}',
  verified: '\u{ef76}',
  payments: '\u{ef63}',
  event_available: '\u{e614}',
  event_busy: '\u{e615}',
  verified_user: '\u{e8e8}',
} as const;

export type IconName = keyof typeof ICON_GLYPHS;
